### Get home api
GET http://localhost:{{PORT}}

### Get api
GET http://localhost:{{PORT}}/api

### Get status conection to printer
GET http://localhost:{{PORT}}/api/print/status

### Post print receipt
POST http://localhost:{{PORT}}/api/print
Content-Type: application/json

{
  "baseOrderURL": "",
    "branch": "MATOVELLE(AZOGUES)",
    "contact": "1234567890",
    "customer": "1234567890",
    "device": "SAMSUNG SM-G973",
    "is_it_returning": "No",
    "keyword": "",
    "name": "JHON DAE",
    "notes": "",
    "order_number": "123456789012345",
    "pattern": "",
    "printerIp": "192.168.0.1",
    "printServer": "192.168.0.100",
    "receivedAt": "",
    "received_by": "VIVI PARAMO",
    "received_by_phone": "1234567890",
    "sketch": "",
    "imei": "9204102431243",
    "isWednesday": true
}
